### ISSUE TITLE
[BUG] There is no Global Properties that sets try-timeout to retry.fixed

### ISSUE THREAD

**Issue by YusukeTobo** [microsoft/spring-cloud-azure#993] opened 2022-09-14 07:25 UTC
**Describe the bug**
As you may see the following doc, there is no Global Properties that sets try-timeout to retry.fixed.
https://microsoft.github.io/spring-cloud-azure/4.3.0/reference/html/appendix.html#global_proeprties

**To Reproduce**
Please use settings in Code Snippet section.
spring.cloud.azure.retry.fixed.try-timeout=10s # not work
#spring.cloud.azure.storage.retry.try-timeout=2s # work but no global properties.

***Code Snippet***
src/main/resources/application.properties
```yaml
spring.cloud.azure.retry.mode=fixed
spring.cloud.azure.retry.fixed.max-retries=108
spring.cloud.azure.retry.fixed.delay=7s
spring.cloud.azure.retry.fixed.try-timeout=10s
#spring.cloud.azure.storage.retry.try-timeout=2s
```

**Information Checklist**

- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by saragluna** [comment] 2022-09-14 12:23
Hi @YusukeTobo thanks for reaching out. This is actually by design, since for some HTTP-based clients, like Key Vault, don't have a tryTimeout. So we add this only for AMQP-based clients and Storage. So there's no global properties for all the SDK clients, but there's one `spring.cloud.azure.retry.amqp.try-timeout`. The one for storage is an exception for HTTP-based client.

**Comment by YusukeTobo** [comment] 2022-09-15 12:04
Hi @saragluna , thank you for letting know that design. I understand HTTP-based clients generally don't support tryTimeout.

**Comment by saragluna** [comment] 2022-09-16 02:59
@YusukeTobo could we close this issue now?

**Comment by YusukeTobo** [comment] 2022-09-19 11:25
@saragluna yes you cloud. BTW, `spring.cloud.azure.client.http.connect-timeout=30s` is not override default timeout 10s in Netty HTTP client. Should I create another issue?

**Comment by saragluna** [comment] 2022-09-20 02:27
@YusukeTobo yes please. Could you create the issue in the [azure-sdk-for-java](https://github.com/Azure/azure-sdk-for-java/issues/new/choose) repo?

**Closed by saragluna** 2022-09-20 02:27 UTC
Labels: question, azure-spring, azure-spring-4.0, client

**Comment by YusukeTobo** [comment] 2022-09-20 12:58
@saragluna building on this issue, I've filed 2 reports related to Connect Timeout. If possible, could you look into them?

1. https://github.com/Azure/azure-sdk-for-java/issues/31051
2. https://github.com/Azure/azure-sdk-for-java/issues/31052

**Comment by saragluna** [comment] 2022-09-20 13:21
Thanks @YusukeTobo for filing them, we will look into these two issues.
