### ISSUE TITLE
ASA Pricing with enterprise Tiers shows it is Free wheras it is now GA

### ISSUE THREAD

**Issue by ezYakaEagle442** [microsoft/spring-cloud-azure#979] opened 2022-07-13 08:21 UTC
Azure Spring Apps is now GA, no more Preview.

**Screenshots**

![ASA_EnterpriseèTier_Free_preview](https://user-images.githubusercontent.com/43554247/178685958-f6a0c3d3-5d40-482e-9c85-fd0080861e9b.png)

See at [https://azure.microsoft.com/en-us/pricing/calculator/](https://azure.microsoft.com/en-us/pricing/calculator)

**Comment by chenrujun** [comment] 2022-07-13 09:46
@ezYakaEagle442 

Thanks for reaching out.
This problem does not exist in my side.
Here is the screenshot:
![image](https://user-images.githubusercontent.com/13167207/178704375-1a6dcbf2-15f0-4fc8-af9c-2f29d2079ab0.png)

Please try to refresh your page.

**Comment by ezYakaEagle442** [comment] 2022-07-14 13:21
@chenrujun this is because your screenshot shows the standard Tier is selected, NOT the Enterprise Tier.
Check on your side please, selecting Enterprise Tier.

**Comment by chenrujun** [comment] 2022-07-15 00:50
Closing this issue because the issue is tracked here: [https://dev.azure.com/azurecom/ACOM/_workitems/edit/186630](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fazurecom%2FACOM%2F_workitems%2Fedit%2F186630&data=05%7C01%7CAzureSpringCloud-Talk%40service.microsoft.com%7Cb7cf87aac4ff4f653fe208da65972fab%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637933997345798339%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rXl%2FpY1slo9HaY51j8sE2DtBFkC5GW1ZeCWBfMK1ONQ%3D&reserved=0)

**Closed by chenrujun** 2022-07-15 00:50 UTC
Labels: azure-spring
