### ISSUE TITLE
[BUG] Java dependency conflicts when use spring-cloud-azure-starter-keyvault-secrets in Spring Boot 3

### ISSUE THREAD

**Issue by seyiayeni** [microsoft/spring-cloud-azure#1053] opened 2023-03-13 22:44 UTC
I am getting the following NoSuchMethodError error while using version 5.0.0 of the keyvault-secrets package.
implementation 'com.azure.spring:spring-cloud-azure-starter-keyvault-secrets:5.0.0' in spring boot 3.0.4 and Java 17.

java.lang.NoSuchMethodError: 'reactor.core.publisher.Mono reactor.core.publisher.Mono.subscriberContext()'

Seems the subscriberContext was removed in rector 3.5 which spring boot 3 now uses and spring-cloud-azure still uses the old version of reactor

Will there be support for support for Spring boot 3 anytime soon?

**Comment by chenrujun** [comment] 2023-03-14 02:54
Hi, @seyiayeni 

Thanks for reaching out.
`spring-cloud-azure-starter-keyvault-secrets:5.0.0` should support `Spring Boot 3` well.
`spring-cloud-azure-starter-keyvault-secrets:5.0.0` depends on `reactor-core:3.5.3`. Here is the screenshot of my `build.gradle` and dependency tree:

> ![image](https://user-images.githubusercontent.com/13167207/224880745-10d6397c-970e-490a-903f-275b62bce36c.png)

I think the following error is not caused by `spring-cloud-azure-starter-keyvault-secrets:5.0.0`.

> java.lang.NoSuchMethodError: 'reactor.core.publisher.Mono reactor.core.publisher.Mono.subscriberContext()'

Could you please share your `build.gradle` file?

**Comment by seyiayeni** [comment] 2023-03-14 15:31
Hello @chenrujun 

Here is my build.gradle file

`
plugins {
	id 'java'
	id 'org.springframework.boot' version '3.0.4'
	id 'io.spring.dependency-management' version '1.1.0'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '17'

repositories {
	mavenCentral()
}

dependencies {
	annotationProcessor "org.projectlombok:lombok:1.18.24"
	annotationProcessor "org.mapstruct:mapstruct-processor:1.18.24"
	annotationProcessor "org.projectlombok:lombok-mapstruct-binding:0.2.0"
	implementation "org.projectlombok:lombok:1.18.24"
	implementation "org.apache.commons:commons-lang3:3.11"
	implementation 'org.springframework.boot:spring-boot-starter-webflux'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation "org.springframework.boot:spring-boot-starter-webflux"
	implementation "org.springframework.boot:spring-boot-starter-actuator"
	implementation "org.springframework.boot:spring-boot-starter-validation"
	implementation "com.azure.spring:spring-cloud-azure-starter-keyvault-secrets:5.0.0"

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
}

tasks.named('test') {
	useJUnitPlatform()
}
`



But I also noticed when I checked the dependencies tree, the spring-cloud-azure is pulling in reactor 3.4.23


<img width="878" alt="Screenshot 2023-03-14 at 8 30 03 AM" src="https://user-images.githubusercontent.com/29350964/225052654-1c2b1992-3b77-4076-8780-2d7b9f19d2a3.png">

**Comment by saragluna** [comment] 2023-08-25 07:11
We have chosen to use the same sdk bom for Spring Boot 2.x and 3.x, and Spring Cloud Azure has released 5.4.0. Closing this issue now. Please reopen it if you are still facing this issu.e

**Closed by saragluna** 2023-08-25 07:11 UTC
Labels: azure-spring
