### ISSUE TITLE
Unable to connect to event hub

### ISSUE THREAD

**Issue by rahuly-fragma** [microsoft/spring-cloud-azure#649] opened 2020-03-22 06:33 UTC
with protocol : 9093
Invalid SASL mechanism response, server may be expecting a different protocol
Caused by: org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'auth_bytes': Bytes size -1 cannot be negative

**Comment by saragluna** [comment] 2020-03-23 12:55
Thanks for reaching out. I assume you're using the Event Hub Kafka binder, but could you provide more details for me to reproduce this issue? Which version of the library you're using?

**Comment by rahuly-fragma** [comment] 2020-03-23 14:14
@saragluna thanks for responding .
<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>spring-cloud-azure-starter-eventhub</artifactId>
			<version>1.0.0.M2</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-stream-kafka</artifactId>
			<version>3.0.3.RELEASE</version>
		</dependency>

These are the version i'm using for the connection.

**Comment by saragluna** [comment] 2020-03-25 13:18
Have you tried with the Event Hub Kafka binder?  Here's the sample project https://github.com/microsoft/spring-cloud-azure/tree/master/spring-cloud-azure-samples/eventhubs-kafka-sample.

**Comment by rahuly-fragma** [comment] 2020-03-25 13:51
Dear Team,

I have tried the above mentioned sample .Though  its giving the same
error.I'm not able to figure out first what is the root cause of the issue .
Will  it throw this error  if my *.azureauth file is not correct?

Thanks & Regards
Rahul Yadav

**Comment by saragluna** [comment] 2020-04-07 02:43
Sorry for the late response. It's more like that the Kafka could not be authorized correctly. Are you experimenting with Event Hub using the Kafa protocol?

**Comment by saragluna** [comment] 2020-04-24 08:07
Close this issue since no recent update.

**Closed by saragluna** 2020-04-24 08:07 UTC
Labels: Event Hub

**Comment by tyipfadv** [comment] 2021-04-02 21:29
any update?  I went into the same issue when using Kafka connect.   I followed this MS page.  https://github.com/Azure/azure-event-hubs-for-kafka/tree/master/tutorials/connect

**Comment by saragluna** [comment] 2021-04-12 03:59
@tyipfadv we've deprecated this repo, could you create an issue in the new [azure-sdk-for-java](https://github.com/Azure/azure-sdk-for-java) repo and describe the issue you encountered?
