### ISSUE TITLE
Auto configure does not generate metadata json file

### ISSUE THREAD

**Issue by sophiaso** [microsoft/spring-cloud-azure#421] opened 2019-01-02 09:05 UTC
[Spring Configuration Metadata](https://docs.spring.io/spring-boot/docs/current/reference/html/configuration-metadata.html)

Application properties/yaml should support auto complete for the properties in this project, currently not supported.

**Comment by saragluna** [comment] 2020-07-22 03:26
Already implemented (but had a regression when migrated to the azure-sdk-for-java repo). Closing this one since already tracked with https://github.com/Azure/azure-sdk-for-java/issues/13264.

**Closed by saragluna** 2020-07-22 03:26 UTC
Labels: New feature, azure-spring
